// <auto-generated />
using System;
using CF_ABCCenter.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CF_ABCCenter.Migrations
{
    [DbContext(typeof(ABCCenterDbContext))]
    partial class ABCCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CF_ABCCenter.Models.Languages.LanguageModel", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CF_ABCCenter.Models.Levels.LevelModel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("LevelId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            IsDelete = false,
                            LevelName = "A"
                        },
                        new
                        {
                            LevelId = 2,
                            IsDelete = false,
                            LevelName = "B"
                        });
                });

            modelBuilder.Entity("CF_ABCCenter.Models.Students.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("IMG");

                    b.Property<bool>("IsDelete");

                    b.Property<int>("LanguageId");

                    b.Property<int>("LevelId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Sex");

                    b.HasKey("StudentId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LevelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CF_ABCCenter.Models.Students.StudentModel", b =>
                {
                    b.HasOne("CF_ABCCenter.Models.Languages.LanguageModel", "Languages")
                        .WithMany("Students")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CF_ABCCenter.Models.Levels.LevelModel", "Levels")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
