CREATE DATABASE QuanLyNhanVien
GO
​
USE QuanLyNhanVien
GO
​
CREATE TABLE PhongBan (
	ID INT PRIMARY KEY IDENTITY,
	MaPhongBan NVARCHAR(5) UNIQUE NOT NULL,
	TenPhongBan NVARCHAR(50) NOT NULL,
	DaXoa BIT DEFAULT 0 NOT NULL
)
GO
​
CREATE TABLE NhanVien (
	MaNV INT PRIMARY KEY IDENTITY,
	PhongBanId INT FOREIGN KEY REFERENCES dbo.PhongBan(ID),
	Ho NVARCHAR(20) NOT NULL,
	Ten NVARCHAR(20) NOT NULL,
	DiaChi NVARCHAR(250) NOT NULL,
	DienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50),
	DaXoa BIT DEFAULT 0 NOT NULL,
	NgayTao DATE,
	NgaySua DATE
)